### ISSUE TITLE
Sorry to bug you like this...5e Com Pack

### ISSUE THREAD

**Issue by Fenris447** [shadowchemosh/Shadowd20#1]
Hey Shadow, sorry to barge in on your personal GitHub! I sent you a PM a few days ago on the forums that the 5e Community Pack’s next release is ready. I’m sure you’re busy so you didn’t see it. With the forums down for who knows how long, this is the only way I could think of to get in touch with you. No rush on getting it pushed, just wanted to get it in front of you.

Also, if there’s anything I can do to make the release process quicker and easier for you each time, please let me know! You’re doing us all a huge favor by hosting and pushing it each time, so I’d like to ease that burden as much as possible. 

How exactly does it work, anyway? Are you actually hosting a server with the info that we all connect to? If that hosting has a cost to you, thank you again. Let me know if you have a PayPal or something for your hosting costs so I can chip in a thank-you.

**Comment by shadowchemosh** [comment]
Hi Frenris447... No issues contacting me this way. Feel free in the future to simply email me at my HL Forum User ID @ yahoo dot com.

I did see the message but have been really busy at work.  I plan to do the release Sunday as I should be able to make some time.

I am actually hosting that site (ie shadowsoftware.net) and it does have a cost to it that I pay each year. Its honestly not much at all and why I appreciate the idea of giving money its not required in anyway.  I am actually hosting the data for Pathfinder, 5E and the d20 HL community data sets.

Can't think of much in the way to make things easier.  If you could email the link to the release notes again that would be helpful I am always misplacing it. =)

Thanks!

**Comment by Fenris447** [comment]
Thanks for the help, sir!
